### ISSUE TITLE
First Lanch Issue 

### ISSUE THREAD

**Issue by safiresh** [MLstate/PEPS#50]
hi Team, 
I am try setup peps on my own server. 
i ad installed  and configuration also did well but .. 
i am going to setup admin passsword  getting this issue :( 
kindly check revert to me.  what  i did wrng pls help me  :) 

DbUtils:  Adding admin user with email "Administrator" <admin@liad.in>
[User] add: adding user admin
Uncaught exception : Error: nacl.util moved into separate package: https://github.com/dchest/tweetnacl-util-js
Error: nacl.util moved into separate package: https://github.com/dchest/tweetnacl-util-js
    at Object.nacl.util.decodeUTF8.nacl.util.encodeUTF8.nacl.util.encodeBase64.nacl.util.decodeBase64 (/usr/local/lib/node_modules/tweetnacl/nacl-fast.js:2164:11)
    at global.Servernacl_nacl_util_decodeUTF8 (/peps/_build/servernacl.opp/servernaclNodeJsPackage.js:62:79)
    at Object.<anonymous> (/peps/_build/com.mlstate.webmail.model.opx/main.js:2579:112)
    at global.execute_ (/opa/usr/local/lib/opa/static/opa-js-runtime-cps/main.js:19:49)
    at global.execute1 (/opa/usr/local/lib/opa/static/opa-js-runtime-cps/main.js:20:50)
    at Object.global.loop_schedule [as _onImmediate] (/opa/usr/local/lib/opa/static/opa-js-runtime-cps/main.js:37:339)
    at processImmediate [as _immediateCallback] (timers.js:330:15)

**Comment by safiresh** [comment]
i found  the issue reason .
we are used tweetnacl npm modules. we are forget metion the version name instead of "*" . they released new version v0.14.0 they split the util method on separate npm  modules so this issue happened

**Comment by hbbio** [comment]
Confirmed, thanks for the report. We are looking at the best option, meanwhile you can specify manually an older version of TweetNaCl.

**Comment by welsh4evr** [comment]
Temporary workaround is in 
`peps/Dockerfile`
on line 23 change 
`tweetnacl \` TO `tweetnacl@0.13.3 \`

**Comment by Afrowave** [comment]
@welsh4ev I tried your workaround and found it is when you "clone" PEPS that one should change the tweetnacl and NOT after building and failing.

**Comment by welsh4evr** [comment]
@Afrowave Yeah sorry, forgot to say that you have to run make build again after changing the file.
